# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda73846274776654e57680d7b40e60fccff9460ddd44f3308295f976808c31ec40b94c596dfc990921ec7d019883a6a0284a857b7b1aab5250391dbdfa5f69f

test:
  secret_key_base: 822e72186047f7651a41da95bf6300cebb797cb5097488054bfb91d7369bad6563c3b7ff0e3ba2d392d06c71a051ad1737ec6d1cd6cdabaef87f8e6d8f834be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
